MoTrPAC/motrpac-frontend

- src/LandingPage/landingPage.jsx
- Updated the landing page animation to the most recent version.
> Update landing page animation to most recent version

- src/App/App.jsx
- src/App/reducers.js
- src/Auth/Auth.js
- src/Navbar/navbar.jsx
1. Suppress **TEST VERSION** tiled background image.
2. Show yellow **Alpha** badge in header throughout site.
3. Only show top red banner with test message on homepage.
> Update alpha release and test message UIs

- src/AnalysisPage/animalPhenotypeData.jsx
1. New calculation for the boxplot whiskers' min/max values.
2. Outliers of the boxplot are being shown.
3. The width of the boxplot graph is reduced for readability.
> MOTR-95 Data visualization boxplot enhancement

- src/DownloadPage/downloadPaginator.jsx
- src/GoogleAnalytics/googleAnalytics.jsx
- reduce variations in analytics URLs (alpha.URL registers as `alpha`, alpha-something.URL as `dev` in GA)
- to test: start local server 
- edit `/etc/hosts` on your machine
- add `127.0.0.1       alpha-something.motrpac-data.org`
- go to http://alpha-something.motrpac-data.org:3000
- check google analytics page... should show as 1 active user on dev on GA
- suppress page num nav display on downloads page temporarily (needs attention, nav arrows still display)
> MOTR-100 update analytics, change paginator

- src/ContactPage/contact.jsx
Key changes:
1. added 3rd box for general inquiries
> MOTR-114 Update Contact us page

- src/ContactPage/contact.jsx
changes the team name 'the MoTrPAC Bioinformatic Center '
> MOTR-114 updating contact us page 2

- src/DataSummaryPage/dataSummaryPage.jsx
- src/ReleasePage/releaseEntry.jsx
- src/ReleasePage/releases.json
- src/sass/dataRelease/_releasePage.scss
1. Added disclaimer to sample tracking/summary page.
2. Added internal patch release (aka Release 1.1) UIs to the release page.
3. Added UI control to show/hide the UIs of prior releases.
4. Refactored UI rendering code to be metadata-driven.
> MOTR-154 Tracking/Summary Page Disclaimer

- src/ReleasePage/releases.json
1. Updated metadata for documentation UI rendering in each of the releases.
> MOTR-154 Internal Patch Release Candidate Fixes

- src/DataAccess/dataAccessPage.jsx
- src/DataAccess/response.jsx
- src/Navbar/navbar.jsx
- src/ReleasePage/releaseEntry.jsx
- src/ReleasePage/releases.json
- src/lib/studyDocumentsTable.jsx
- src/sass/dataRelease/_releasePage.scss
1. Include e-signature in the user data object posted to backend service.
2. Include version of the embargo agreement in the user data object posted to backend service.
3. Include the embargo agreement consent date in the user data object posted to backend service.
4. Support multiple spaces and special characters in e-Signature and other name fields on Data Access page. 
5. Make MoTrPAC study docs available to users upon login.
6. Add the display of Auth0-specific error message if an existing registered user tries to register again.
> MOTR-169 External Release Fixes

- src/ContactPage/contact.jsx
- src/LandingPage/landingPage.jsx
- src/ReleasePage/releases.json
- src/Search/searchResultFilters.jsx
- src/Search/searchResults.jsx
1. Updated general data access inquiry wording on homepage and contact page.
2. Updated internal release 1.2 zipped file sizes.
> Minor fixes for external release

- src/DataAccess/dataAccessPage.jsx
- src/ReleasePage/releaseEntry.jsx
Tweaks to display/fix typo on:
- `src/DataAccess/dataAccessPage.jsx`
- `src/ReleasePage/releaseEntry.jsx`
> last external release tweaks

- src/sass/_analysisPage.scss
- src/sass/analysis/_metaAnalysis.scss
Minor responsive styling adjustment on analysis pages for larger mobile device screens.
> MOTR-170 Additional fixes for RC

- README.md
1. Added Sauce Labs build status badge to README.
2. Added CircleCI build status badge to README.
3. Added text link to Sauce Labs at the end of README.
4. Replaced **motrpac-frontend** header text with MoTrPAC Data Hub logo image.
**Steps to test:**
See the `README.md` of this branch at https://github.com/AshleyLab/motrpac-frontend/tree/MOTR-193_JZ_Readme_Attribution_SauceLabs
> MOTR-193. Sauce Labs and CircleCI attributions.

- package.json
- src/Auth/Auth.js
- src/ContactPage/contact.jsx
- src/ErrorPage/error.jsx
- src/LandingPage/landingPage.jsx
- src/Widgets/allUploadsDoughnut.jsx
- src/lib/studyDocumentsTable.jsx
- src/lib/ui/contactHelpdesk.jsx
- src/lib/ui/emailLink.jsx
- src/sass/_landingPage.scss
- src/sass/_links.scss
- src/sass/_studyDocumentTable.scss
- src/sass/dataAccess/_dataAccessPage.scss
- src/sass/dataRelease/_releasePage.scss
- src/sass/main.scss
1. Removed `tinycolor2` npm module due to its limited use case in the app.
2. Implemented a shared library component to render MoTrPAC Helpdesk contact text consistently.
3. Refactored the implementation of the shared MoTrPAC study documents table component so that the table cells in the same row can be responsively stacked in smaller viewports.
4. Changed the Auth0 implementation so that it no longer auto-renew the access-token.
5. Upgraded some npm modules to their latest versions.
**Steps to test MOTR-94:**
1. Sign into the data hub app and go to `^/dashboard` in the browser.
2. In the "doughnut" chart on the page, expect to see no borders in the chart.
**Steps to test MOTR-121:**
1. Without signing into the data hub app, go to the homepage and scroll to the bottom of …
> MOTR-94 MOTR-121 MOTR-182 MOTR-192

- src/LandingPage/landingPage.jsx
- src/sass/_landingPage.scss
**Key changes:**
1. Added language about non-finalized animal datasets in the release.
2. Adjusted font size and styling for the updated announcement UI.
> MOTR-209 Homepage announcement update

- README.md
Update CircleCI badge to point to new repo location
> update circleci badge location

- src/ReleasePage/releases.json
1. Updated file path metadata for the downloadable zipped files.
> MOTR-263 Internal Release 2 RC Fixes

- src/ReleasePage/releaseEntry.jsx
- src/ReleasePage/releases.json
> fixed download

- src/AnnouncementsPage/announcements.json
- src/AnnouncementsPage/announcementsPage.jsx
- src/LandingPage/landingPage.jsx
- src/ReleasePage/releaseEntry.jsx
- src/ReleasePage/releases.json
1. Implementation of tracking click events in Google Analytics for announcement links on Landing Page.
2. Implementation of tracking click events in Google Analytics for outbound links on Announcement Page.
3. Refactoring of rendering command-line file download source path shown in mouseover tooltips on Release Page.
4. Added `metabolomics-named-merged` to the lists of downloadable zip files on Release Page.
5. Updated the downloadable zip file sizes for the list of omics on Release Page.
> MOTR-263 Internal Release Candidate Enhancement

- src/ReleasePage/releaseEntry.jsx
- src/Sidebar/sidebar.jsx
- src/lib/studyDocumentsTable.jsx
1. Deactivated sidebar link to **Summary Page** due to its content being out-of-date.
2. Suppressed **Data Use Agreement** link/row in the study doc table for internal users.
> MOTR-263 Additional release 2.0 RC fixes

- src/Dashboard/dashboard.jsx
- src/Widgets/releasedSampleHighlight.jsx
- src/Widgets/releasedSampleSummary.jsx
1. Updated code to only render externally released samples data on **Dashboard** for external users.
2. Reworded "GET" to "Genomics" on Dashboard.
**Steps to test:**
1. Sign into your local instance as an _external_ user.
2. Expect to see the Dashboard page with only external release samples data.
> MOTR-269 Release Candidate Bug Fixes

- src/Dashboard/dashboard.jsx
- src/Sidebar/sidebar.jsx
- src/Widgets/plotControls.jsx
- src/Widgets/releasedSampleHighlight.jsx
- src/Widgets/releasedSamplePlot.jsx
1. Fixed typo in the _sidebar_ tooltip.
2. Changed icon for the **Releases** nav link in the sidebar.
3. Renamed instances of "assays" to "platforms" on **Dashboard**.
4. Renamed instances of "samples" to "assays" on **Dashboard**.
**Steps to test:**
1. Sign into your local instance of this branch.
2. Expand the sidebar. Expect to see the tooltip for the "Close" icon at the top of the sidebar reads "Collapse" instead of "Collpase".
3. Also expect to see the icon for the "Releases" sidebar nav link is _cloud with check mark_.
4. On the Dashboard page, expect to see instances of "platforms" replacing the previously named "assays".
5. Also expect to see instances of "assays" replacing the previous named "samples".
> Connects to #81 Minor UI fixes in Sidebar and Dashboard

- src/Dashboard/dashboard.jsx
- src/Widgets/releasedSampleHighlight.jsx
- src/Widgets/releasedSamplePlot.jsx
- src/sass/dashboard/_dashboard.scss
1. Responsive  UI changes to render equal heights of box of highlighted metrics as well as their content pertinent to smaller viewport widths.
2. Reduced plot x-axis label text size when viewport width is smaller than 620px in attempt to avoid label overlappings.
> Connects to #84. Connects to #83. UI enhancement to highlighted metrics boxes

- src/DataAccess/dataAccessPage.jsx
1. Bumping embargo agreement version number for the submitted JSON object property.
> Bumping embargo agreement version

- src/DataAccess/dataAccessPage.jsx
- src/ReleasePage/releaseEntry.jsx
- src/ReleasePage/releasePage.jsx
Display notices on user registration page and data releases page about their temporary unavailability.
> Connects to #148. Service temporarily unavailable notices.

- src/DataAccess/dataAccessPage.jsx
- src/RelatedStudy/heritageProteomics.jsx
- src/ReleasePage/releaseEntry.jsx
- src/ReleasePage/releasePage.jsx
1. Replaced 2 prior container-based backend services (that support data download and user registration on data hub portal) with serverless API endpoints implemented with the **Load Balancer**, **API Gateway**, and **Cloud Functions** resources provisioned using **Terraform**.
2. Removed prior service unavailability notices and re-enabled download links and user registration.
3. Updated citation for HERITAGE study paper that has been published.
> Connects to #150. Connects to #151. New API service endpoints and HERITAGE study citation update.

- src/AnalysisPage/analysisActions.js
- src/Auth/auth0-variables.js
- src/BrowseDataPage/browseDataActions.js
- src/DataAccess/dataAccessPage.jsx
- src/Navbar/navbar.jsx
- src/ReleasePage/releaseEntry.jsx
- src/Search/searchActions.js
- src/Search/searchPage.jsx
- src/Sidebar/sidebar.jsx
- src/setupProxy.js
* Implemented handling to call the respective service API endpoints via `GET` requests when users visit the **Data Access** and **Releases** pages. The attempt is to _warm up_ the Cloud Functions to address the _cold start_ scenario.
* Set the `size` param to `0` for the search request on generating the downloadable zip file of search results. The goal is to minimize the amount of response data size.
* Implemented a workaround to shorten the amount of time required to fetch all **PASS1B-06** data object metadata to render the **Browse Data** UIs. The metadata is now fetched from ElasticSearch instead of NoSQL database.
* Refactored hardcoded service API URLs to use conditional environment variables.
* Removed deprecated implementation of quick search in the `navbar` component.
> Connects to #166. Connects to #167. Cloud Functions and search enhancements.

- src/BrowseDataPage/components/bundleDataTypes.js
- src/Search/featureLinks.jsx
- src/sass/_landingPage.scss
* Add misc analysis resources bundle to downloadable PASS1B-06 bundle data sets
* Set "Open Sans" font for the main tagline on the landing page
> Connects to #226. Misc analysis resources bundle data set.

- .circleci/config.yml
- src/LandingPage/promoteBanner.jsx
- src/MethodsPage/methods.jsx
- src/Navbar/navbar.jsx
- src/lib/studyDocumentsTable.jsx
- src/sass/_landingPage.scss
- src/sass/_navbar.scss
* Added new announcement banner on landing page for upcoming open office hour on 6/22.
* Created Google Form for external users to sign up.
* Updated homepage CSS to handle UI responsiveness in different viewport sizes.
> Connects to #241. Open office hour announcement.

- package.json
- src/AnnouncementsPage/announcements.json
- src/GoogleAnalytics/googleAnalytics.jsx
- src/LandingPage/announcementBanner.jsx
- src/LandingPage/landingPage.jsx
- src/LandingPage/promoteBanner.jsx
- src/Navbar/navbar.jsx
- src/sass/_landingPage.scss
- src/sass/_navbar.scss
- The Office Hour banner has been moved towards the bottom of the homepage
- The primary announcement banner at top has been made a bit more prominent
- Google Universal Analytics to Google Analytics 4 migration
> Connects to #244. Connects to #245. GA4 migration and office hour banner.

- src/Tutorials/tutorials.jsx
- src/sass/_base.scss
* Added the embedding of Data Hub tutorial video served from Google Drive
* Fixed UI bug in which top nav covering body content on smaller device screens
> Connects to #243. Data Hub tutorial video.

- src/Navbar/navbar.jsx
- src/Search/featureLinks.jsx
- src/sass/_navbar.scss
- src/sass/search/_search.scss
1. The 3 top level nav items - **QC Data Monitor**, **Prior Data Releases** and **Sample Summary** have been moved into the dropdown menu of **Data Access**, in the attempt to address a few top nav UI issues in smaller viewport sizes:
* The wrapping of **QC Data Monitor** link text, as well as the wrapping of logged-in user profile and logout button, cause the top nav to expand downward and cover up the page content towards the top of the page.
* The addition of top nav items, upon logging in, cause the MoTrPAC logo size to decrease.
2. Set the MoTrPAC logo in the top nav by pixel in size so that it no longer expands or contracts regardless of viewport sizes.
3. Remove the display of logged-in user's full name in top nav. Instead, it will be shown in a dropdown menu when user clicks on …
> Connects to #246. UI fixes.

- .circleci/config.yml
- package.json
- src/ContactPage/contact.jsx
- src/ContactPage/contactForm.jsx
- src/LandingPage/promoteBanner.jsx
- src/Navbar/navbar.jsx
- src/sass/_contact.scss
* Added browser-based contact form on **Contact Us** page
* Removed other prior contact information due to the addition of contact form
* Clicking the Contact Us top nav menu item triggers a GET request to warm up Cloud Function backend
* Bumped versions of React app's dev dependencies
* Bumped version of Circle CI docker image
> Connects to #237. Contact form.

- src/LandingPage/promoteBanner.jsx
Corrected the August virtual Office Hour from Tuesday to Thursday.
> Connects to #255. Wrong day for August Office Hour.

- src/LandingPage/landingPage.jsx
* Fixed link in button on homepage to video tutorials page
> Fix bug in link to video tutorial

- src/MultiOmicsWorkingGroups/multiOmicsWorkingGroups.jsx
Update Google Doc link to DAWG-PAC analysis report.
> DAWG-PAC analysis report link

- src/MultiOmicsWorkingGroups/htmlReportModal.jsx
Added button in the multi-omics working group resources modal for users to download the dawg-pac data analysis reports (HMTL files).
> Connects to #291. Button UI in modal to download analysis reports.

- src/App/App.jsx
- src/App/__test__/App.test.jsx
- src/Navbar/navbar.jsx
- src/Publications/Docs/Protocol/Clinical/clinicalStudyProtocols.jsx
* Converted the previously implemented clinical study protocol and MOP docs page from protected page to publicly accessible.
> Connects to #307. Clinical study protocol docs page public access.

- package.json
- src/AnalysisPage/GraphicalClustering/graphicalClusteringPage.jsx
- src/AnnouncementsPage/announcements.json
- src/Publications/publications.jsx
- src/sass/_landingPage.scss
* Add published mitochondria paper to Publications page
* Add published mitochondria paper to Announcements page
* Updated links to the published landscape and mitochondria papers on Graphical Clustering pages
* Added responsive styling for homepage to improve display in iPhone 12/13 viewports
> Connects to #328. Mitochondria paper in publication.

- src/LandingPage/landingPage.jsx
- src/Tutorials/tutorials.jsx
* Updated links for tutorial video on homepage and tutorial page
> Connects to #340. Update tutorial video link.

- src/AnalysisPage/GeneCentricViewRat/geneCentricViewPage.jsx
- src/AnalysisPage/pass1b06PhenotypeAnimal.jsx
- src/AnnouncementsPage/announcementsPage.jsx
- src/CodeRepoPage/codeRepoPage.jsx
- src/ContactPage/contact.jsx
- src/DataAccess/dataAccessPage.jsx
- src/DataStatusPage/dataStatusPage.jsx
- src/DataSummaryPage/dataSummaryPage.jsx
- src/LinkoutPage/linkoutPage.jsx
- src/MainStudy/mainStudy.jsx
- src/MethodsPage/methods.jsx
- src/Navbar/navbar.jsx
- src/RelatedStudy/relatedStudy.jsx
- src/ReleasePage/releasePage.jsx
- src/TeamPage/teamPage.jsx
* Added a new "Data Updates Signup" menu item in the "Data Access" top nav link dropdown menu. This new menu item opens a Google Form for anyone to subscribe to MoTrPAC data updates.
* Added document titles in the `<head>` element for a number of pages to improve user navigation experience and Google Analytics tracking.
> Connects to #350. Data updates signup.

- src/App/App.jsx
- src/BrowseDataPage/browseDataActions.js
- src/BrowseDataPage/browseDataPage.jsx
- src/BrowseDataPage/browseDataReducer.js
- src/BrowseDataPage/components/dataDownloadsMain.jsx
- src/BrowseDataPage/components/selectiveDataDownloadFileBrowser.jsx
- src/BrowseDataPage/components/selectiveDataDownloads.jsx
- src/BrowseDataPage/helper.jsx
- src/MainStudy/overview.jsx
- src/Navbar/navbar.jsx
- src/Search/featureLinks.jsx
- src/Search/searchPage.jsx
- src/data/file_download_metadata/human_precovid_sed_adu_minified.json
- src/data/file_download_metadata/rat_acute_exercise_6mo_minified.json
- src/data/file_download_metadata/rat_endurance_training_6mo_minified.json
* The customized file download feature is no longer using the search service as the data source for file metadata.
* The customized file download feature is now embedding the file metadata collections in the app to reduce extra layer of complexity due to the small dataset sizes.
* Replaced `v1.0` version of PreCAWG analysis data files with the newer `v1.2` version.
* Corrected typo in `Humnan Adipose Powder` tissue name for PreCAWG data files.
* Refactored customized file download feature code to improve filtering results.
> Connects to #386. File download refactor and new version of precawg data.

- src/MultiOmicsWorkingGroups/dawgPAC.jsx
- src/lib/teamInfo.js
* Updated DAWG-PAC data analysis working group resources section text content and its organization
* Updated Team page content
> Connects to #388. DAWG-PAC data analysis resources update.

- src/Footer/footer.jsx
- src/LandingPage/landingPage.jsx
- src/lib/ui/complianceReviewNotice.jsx
- src/sass/_footer.scss
- src/sass/_landingPage.scss
1. Added a Bootstrap toast UI component displaying the compliance review notice on the homepage. Th toast UI is _sticky_ to the lower right hand corner of the browser window.
2. Added the compliance review notice text to the footer of all pages except the homepage.
> Connects to #398. Compliance review notice.

- package.json
- src/Auth/Auth.js
- src/Search/featureLinks.jsx
- src/Search/sharedlib.jsx
- src/setupTests.js
- yarn.lock
* In PreCAWG DA search results, constructed links for feature IDs consisting of feature-specific query params to be passed to the PreCAWG data-viz URL for rendering single plot for the feature.
* In PreCAWG DA search results, constructed links for genes and metabolites consisting of a query param to be passed to the PreCAWG data-viz URL for rendering single relevant plots for the gene or metabolite.
* For links in the PreCAWG DA search results, included param to be passed in the PreCAWG data-viz URL for validating users.
* For the PreCAWG data-viz quick link on the Dashboard page,  included param to be passed in the PreCAWG data-viz URL for validating users.
> Connects to #400. Feature ID links in PreCAWG DA search results.

- src/MultiOmicsWorkingGroups/dawgPAC.jsx
* Updated text label for link to DAWG-PAC data freeze release notes doc in MAWG section on Data Hub
> Connects to #402. DAWG-PAC data freeze.
