MoTrPAC/motrpac-frontend

- .circleci/config.yml
Note: for early stage development yarn.lock is not versioned so npm/yarn package cache can't be restored. See note in file to change.
Note2: for early stage development storybook snapshots are not not version-controlled, so snapshot testing is not being done in CI. See note in file to change.
> MOTR-51 add JS tests to CI, no snapshot testing, no npm cache restore

- .circleci/config.yml
- Removing the check for `yarn.lock` in the JS dependencies cache restore because we do not use that currently and it throws a warning. 
- Enabled fallback to restore the most current version of the JS dependencies cache since we are not versioning JS cache.
_Note: we can remove the fallback restore if it causes curious behaviors since it only saves a small amount of time right now_
_Note2: `yarn.lock` versioning will be used for production builds and the explicit yarn.lock cache can be re-enabled at that time_
> update CircleCi JS dependencies cache restore via yarn.lock

- package.json
- src/Auth/Auth.js
- src/Auth/auth0-variables.js
- src/Footer/footer.jsx
- src/Navbar/navbar.jsx
1. Refactored the `callbackUrl` option in the  `auth0-variables.js` file so that it is not hardcoded to `localhost`.
2. Refactored the `Auth` class by switching to the use of `expiresAt` class variable from the local class method variables.
3. Removed unnecessary `proxy` option in `package.json`.
> MOTR-80 Refactor Auth0 Callback URL

- src/ReleasePage/releases.json
**Key Change**
- Updated file sizes from KiB/MiB/GiB to KB/MB/GB for downloads in the external release v1.0
**Calculations**
As I did not have view access to motrpac-external-release1-results via gsutil, I asked Young to send me a screenshot from the console and calculated based off of that:
- Epigenomics
8.28 GiB = 8.89 GB -> 9 GB
- Transcriptomics
50.3 MiB = 52.74 -> 53 MB
- Metabolomics Targeted
21.48 MiB = 22.52 -> 23 MB
- Metabolomics Untargeted
96.29 MiB = 100.97 MB -> 101 MB
- Proteomics
283.73 MiB = 297.51 MB -> 298 MB
- Phenotype
497.56 KiB = 509.50 KB -> 510 KB
- All
8.73 GiB = 9.37 GB -> 9 GB
> MOTR-168 Updated KiB/MiB/GiB to KB/MB/GB for External Release 1.0

- src/ErrorPage/error.jsx
- src/LandingPage/landingPage.jsx
- src/ReleasePage/releaseEntry.jsx
- src/sass/_errorPage.scss
- src/sass/_landingPage.scss
- src/sass/main.scss
1. Added help text/link to instruct users on ways to extract downloaded files on the Release page.
2. Updated the Error page with instructions individually targeting consortium members and non-consortium users.
3. Replaced the external data release notice on the homepage temporarily with the upcoming webinar notice.
***
**Steps to test MOTR-201:**
1. Go to the homepage and expect to see the NIH-provided text for the webinar notice in place of the external data release notice.
***
**Steps to test MOTR-196:**
1. Sign into the data hub portal as either an internal or external user.
2. Expect to see the "All bundled datasets are compressed (*.tar.gz) and need to be extracted upon downloading..." text towards the top of the Release page.
***
**Steps to test MOTR-199:**
1. Sign …
> MOTR-196 MOTR-199 MOTR-201

- src/AnnouncementsPage/__tets__/announcementsPage.stories.jsx
- src/AnnouncementsPage/announcements.json
- src/AnnouncementsPage/announcementsPage.jsx
- src/App/App.jsx
- src/LandingPage/landingPage.jsx
- src/Navbar/navbar.jsx
- src/ReleasePage/releaseEntry.jsx
- src/sass/_announcementsPage.scss
- src/sass/_landingPage.scss
- src/sass/main.scss
1. Homepage
* Replaced temporary webinar announcement content with original external data release announcement content in blue alert box.
* Added announcement content about RFA and control issues in initial dataset.
2. Release page
* Added language about initial dataset's control issues in the same paragraph of README.
3. Announcements page
* Newly created and accessible in the **About Us** dropdown menu.
* Added 3 announcement items - webinar with links to the recorded video and slide deck, NIH RFA, and external data release.
> MOTR-209 Post-webinar updates

- package.json
- src/AnnouncementsPage/announcementsPage.jsx
- src/sass/_announcementsPage.scss
1. Upgraded `react-scripts` to its latest version to address an error when doing a clean install with 
the removal of the entire `node_modules` directory and the `yarn.lock` file.
2. Brought a number of other dependencies to their latest versions as well.
3. Added responsive styling to the `^/announcements` page so that content can be rendered _properly_ in smaller viewports.
**Steps to test:**
1. Run `rm -r node_modules` at the branch's root level
2. Run `rm yarn.lock` at the branch's root level
3. Run `yarn install`
4. Run `yarn inspect-branch` upon the completion of _Step 3_
5. Expect to see the portal frontend app being rendered properly in the browser without errors.
6. Now go to the `^/announcements` page.
7. Try to adjust the browser window to different width (or …
> MOTR-213 react-scripts upgrade

- src/ReleasePage/releaseDescReadme.jsx
Implemented the README description text that was pending for phenotypic data release.
---
1.  Sign into the portal and proceed to the ^/releases page.
2.  Expect to see the "A README document has been provided summarizing..." text paragraph present in the Release 1.2.1 description section.
> MOTR-256 README description for phenotypic data release

- src/AnnouncementsPage/announcements.json
- src/LandingPage/landingPage.jsx
- src/ReleasePage/ReleaseDataTables/releaseDataTableExternal.jsx
- src/ReleasePage/ReleaseDataTables/releaseDataTableInternal.jsx
- src/ReleasePage/ReleaseDataTables/releaseDataTableInternalByPhase.jsx
- src/ReleasePage/releaseDescReadme.jsx
- src/ReleasePage/releaseEntry.jsx
- src/ReleasePage/releaseRawFilesDownload.jsx
- src/ReleasePage/releases.json
- src/sass/_announcementsPage.scss
- src/sass/_landingPage.scss
- src/sass/dataRelease/_releasePage.scss
1. On the data hub release page, added UIs for the new internal data release.
2. On the landing page, updated the announcement UI for the 1st MoTrPAC Marker paper published in _Cell_.
3. On the announcement page, added a new announcement item for the 1st MoTrPAC Marker paper published in _Cell_.
Because the data structure in this new release is no longer consistent with prior releases, I opted to create variants of a single component that was responsible to render the downloadable release data table regardless internal/external releases. Going forward, these variants will each be responsible to render the release data table given the release type/version.
> MOTR-263 MoTrPAC Internal Release 2.0 UI Updates

- src/ReleasePage/releases.json
1. Updated pass1b-06 phenotype zip file size on **Release Page**.
> MOTR-263 Final release 2 RC fix

- src/ReleasePage/releases.json
Updated the file sizes for the following zipped files after result file corrections:
`motrpac_pass1a-06_proteomics.tar.gz`
`motrpac_pass1a-06_all.tar.gz`
`motrpac_pass1b-06_proteomics.tar.gz`
`motrpac_pass1b-06_all.tar.gz`
> MOTR-263 Post release file size corrections

- src/Dashboard/__test__/dashboard.test.jsx
- src/Dashboard/dashboard.jsx
- src/Dashboard/dashboardActions.js
- src/Dashboard/dashboardReducer.js
- src/Widgets/plotControls.jsx
- src/Widgets/releasedSampleHighlight.jsx
- src/Widgets/releasedSamplePlot.jsx
- src/Widgets/releasedSampleSummary.jsx
- src/Widgets/releasedSampleTable.jsx
- src/Widgets/tableControls.jsx
- src/data/animal_release_samples.json
- src/sass/dashboard/_dashboard.scss
1. Adding QC sample counts to the highlighted totals (e.g. genomics, metabolomics, proteomics) at the top of dashboard page.
2. Adding QC sample counts to dashboard bar plot.
3. Adding option to show/hide QC sample counts in dashboard sample count table.
4. Added doughnut charts to visualize total QC sample counts.
1. Sign into local instance of this branch and go to ^/dashboard.
2. Expect to see the totals of _genomic_ and _metabolomics_ assays are great than those currently seen in production.
3. Expect to see the bar plot showing stacked _study assays_ and _reference standards_.
4. Expect to see a _checkbox_ option to show/hide the _reference standards_ (QC samples counts) in the table.
5. Expect to see 2 new doughnut charts to the right of the page showing the total _reference …
> Connects to #89. Adding QC sample counts to dashboard visualization.

- src/AnalysisPage/plots/bodyFatChange.jsx
- src/AnalysisPage/plots/lactateChange.jsx
- src/AnalysisPage/plots/vo2MaxChange.jsx
- src/AnalysisPage/plots/weightGain.jsx
Fixed typos in descriptions for animal phenotype plots.
To test:
1. Clone this branch to local repo
2. Spin up local instance of portal with `yarn inspect-branch`
3. Navigate to 'Animal' on the left bar, then 'Phenotypic Data'
4. "Registration" should be correctly spelled
> Fixed typos in descriptions of animal phenotypic data plots

- src/Auth/privateRoute.jsx
- src/Dashboard/dashboard.jsx
- src/ErrorPage/error.jsx
- src/Footer/footer.jsx
- src/Navbar/navbar.jsx
1. Users who are either not authenticated or don't have access to the data are now routed to the error page and not the homepage
2. This branch to address issue 92 avoids a flashing error/dashboard page upon login. 
1. Create/use a user who lacks user metadata and attempt to login (either through Google Auth or username/password). You should be routed to the error page without a login button.
2. Create/use a user who does not have access to the data (either through Google Auth or username/password). You should be routed to the error page without a login button.
3. Create/use a user who does have access to the data. You should be routed to the dashboard.
To do:
1. Hide the login button on the error page, or make it so that it is a logout button?
> 92 ct circular redirect updated

- package.json
- src/AnnouncementsPage/announcements.json
- src/Dashboard/dashboard.jsx
- src/DataAccess/dataAccessPage.jsx
- src/ReleasePage/releasePage.jsx
- src/sass/_announcementsPage.scss
1. Updated embargo extension language on **Data Access** page.
2. Added embargo extension entry on **Announcements** page.
3. Added embargo extension alert UI only visible to external users on **Dashboard** page.
4. Added embargo extension alert UI only visible to external users on **Releases** page.
1. Without signing in on the data hub portal, navigate to `^/data-access` and expect to see an updated embargo language (in **bold**).
2. Then navigate to `^/announcements` and expect to see a new entry titled **"Embargo extension"**.
3. Sign in as an external user and expect to see an alert UI pertinent to the embargo extension message on the _Dashboard_.
4. Then navigate to `^/releases` and expect to see an alert UI pertinent to the embargo extension message.
5. Sign out and then sign in …
> Connects to #104. PASS1A data embargo extension.

- src/DataAccess/dataAccessPage.jsx
1. Changing `motrpac-data.org/data-access` to `https://motrpac-data.org` in the MoTrPAC-recommended citation in the spirit of staying consistent with the email version sent to users.
> Minor text edit in MoTrPAC-recommended citation

- src/ReleasePage/ReleaseDataTables/releaseDataTableInternal.jsx
- src/ReleasePage/releaseDescFileExtract.jsx
- src/ReleasePage/releaseDescReadme.jsx
- src/ReleasePage/releaseEntry.jsx
- src/ReleasePage/releases.json
- src/sass/dataRelease/_releasePage.scss
Suppressed the data download links and CLI instructions for the older versions of internal data releases on the **Releases** page. This change does not affect the latest internal data release (v2.0) nor the external data release (v1.0).
1. Prior to reviewing/testing the branch, run `nvm use v14.15.4`.
2. Also, run `rm -fr node_modules/` and `rm -f yarn.lock`. Then run `yarn install`.
3. Create a `.env` file at the root of the local repo working copy and add `ESLINT_NO_DEV_ERRORS=true`.
4. Then run `yarn sass` and `yarn start` next.
1. Sign into your test instance of the Data Hub portal and go to the `^/releases` page.
2. Scroll to the bottom of the page and click on the gray **"Show prior releases"** button.
3. Expect to see all the direct data download links being disabled, and the CLI …
> Connects to #146. Releases page update.

- src/AnalysisPage/GeneCentricViewRat/geneCentricSearchResultFilters.jsx
- src/AnalysisPage/GeneCentricViewRat/geneCentricViewPage.jsx
Patched a bug introduced to the Gene-Centric View page, in which clicking the filters' **Update results** button upon receiving the search results from the top-level gene search would caused an error.
> Connects to #161. Gene-centric view page bug.

- src/BrowseDataPage/browseDataActions.js
Add `size` param to initial data fetch of **Browse Data** to return results beyond the default `10`.
> Fix to increase number of returned results from ElasticSearch

- src/AnalysisPage/analysisReducer.js
Add `size` param to initial data fetch of **Gene Centric View** to return results beyond the default `10`.
> Fix to increase number of returned results from ElasticSearch for Gene Centric View

- src/BrowseDataPage/browseDataActions.js
- src/BrowseDataPage/browseDataPage.jsx
- src/BrowseDataPage/browseDataTable.jsx
* Added documented config to allow users to select all files on **Browse Data** page when clicking on the checkbox in table header. Previously clicking on this checkbox only selects files shown on the current paginated page.
* Added Google Analytics to track individual file download requests when user clicks on the **Download selected files** button.
* Updated message displayed in the file download request modal.
* Removed code previously used for rendering individual data file download links in the modal. Upon the deployment and integration of the file download backend service, the prior implementation is no longer used.
To spin up a local instance, please do the following:
* Requires `node.js v14.18.0` to build the app and run the tests.
* Running `rm -fr node_modules/`, `rm …
> Connects to #183. Connects to #191. Selection of all data files and Googe Analytics for tracking download requests.

- package.json
- src/BrowseDataPage/browseDataFilter.jsx
- src/BrowseDataPage/browseDataPage.jsx
- src/BrowseDataPage/browseDataTable.jsx
- src/BrowseDataPage/helper.jsx
- src/LandingPage/landingPage.jsx
- src/ReleasePage/ReleaseDataTables/releaseDataTableInternalByPhase.jsx
- src/ReleasePage/releaseDescFileExtract.jsx
- src/ReleasePage/releaseDescReadme.jsx
- src/ReleasePage/releaseEntry.jsx
- src/ReleasePage/releases.json
- src/lib/browseDataFilters.jsx
- src/sass/_landingPage.scss
- src/sass/analysis/_geneCentricResults.scss
- src/sass/browseData/_browseData.scss
- src/sass/dataRelease/_releasePage.scss
* Updated the Releases page so that now consortium users no longer can access the prior internally released data. With the newly added note, users are now instructed to visit the Browse Data page to access the most up-to-date PASS1B-06 data.
* On the Browse Data page, the page summary at the top has been expanded so that it is now more descriptive and provides a bit context on the data.
* On the Browse Data page, the order of the Assay and Omics filter group panels have been swapped.
* On the Browse Data page, the Phenotype filter has been moved out of the Category filter group and into its own labeled Metadata.
* On the Browse Data page, an `info` icon has been added to the Category filter group panel header so that it shows/hides a tooltip given the mouseover event.
* Fixed a bug that …
> Connects to #194. Informing users the status of data from prior consortium releases.

- src/BrowseDataPage/browseDataReducer.js
- src/data/animal_release_samples.json
* On the **Browse Data** page, selecting a **non-metabolomics** assay filter would result in a set of files with **merged** metabolomics data included. This has now been addressed with a workaround.
* On the **Sample Summary** page, the sample counts for **PASS1A-06 RNA-seq** _testes_ and _ovaries_ tissues have now been corrected to 39.
> Connects to #204. Connects to #206. Fixes for Browse Data and Sample Summary.

- src/AnalysisPage/GeneCentricViewRat/geneCentricSearchResultFilters.jsx
- src/AnalysisPage/GeneCentricViewRat/geneCentricViewPage.jsx
- src/AnalysisPage/analysisActions.js
- src/AnalysisPage/analysisReducer.js
- src/BrowseDataPage/browseDataPage.jsx
- src/Search/deaSearchResultFilters.jsx
- src/Search/searchPage.jsx
- src/Search/searchReducer.js
- src/sass/search/_search.scss
* Use the unique metadata in the top-level search response (e.g. gene symbol, protein id, metabolite) to disable the search filters (e.g. tissue, assay) that have no matches in the returned DEA results. This change applies to the DEA search and Gene-centric View pages.
* Display a more helpful message to users when selected search filters return no matches in the search results. This change applies to the DEA search, Gene-centric View, and Browse Data pages.
* Fixed uncaught UI behavior when user clicks on the radio buttons of either Gene or Protein ID after a top-level search. Now the click event reset top level search results. This change applies to the DEA search page only.
> Connects to #210. Search user experience enhancement.

- src/DataStatusPage/qcReportByPhaseTabContent.jsx
* Added condition to ignore the metabolomics/proteomics raw file entries in rendering the "tissue submission by phase" grid/matrix of the QC Data Monitor so that the instances of "T* - undefined" (e.g. "T69 - undefined") are omitted from the bottom grid labels.
> Connects to #218. QC Data Monitor bug.

- src/Search/searchReducer.js
- src/Search/sharedlib.jsx
* Removed instances of `dataset` from search params, search props, table props, and table cell value processing, all pertinent to searchable metabolomics DEA results.
> Connects to #220. Search result filter bug for metabolomics assays.

- src/AnalysisPage/analysisActions.js
- src/AnalysisPage/analysisReducer.js
- src/Search/searchActions.js
* When a search submit event is invoked at the top-level, all search filters are reset so that previously selected filters are not persisted. This change applies to the DEA search and Gene-centric View.
> Connects to #227. Reset all search filters.

- package.json
- public/index.html
* Pinned `sass` dependency version to suppress deprecation warning of global abs() function when compiling `scss` files
* Added Clarity tracking code to `<head>` in `public.html` to collect usage stats
> Connects to #259. Clarity tracking code.

- src/AnnouncementsPage/announcements.json
- src/AnnouncementsPage/announcementsPage.jsx
- src/BrowseDataPage/browseDataActions.js
- src/BrowseDataPage/components/bundleDownloadButton.jsx
- src/GoogleAnalytics/googleAnalytics.jsx
- src/LandingPage/announcementBanner.jsx
- src/LandingPage/promoteBanner.jsx
- src/ReleasePage/releaseEntry.jsx
- src/Search/searchPage.jsx
* Added event tracking parameter to GA4 to capture downloaded file list
* Updated event action values for various targeted events since GA4 only allows 40-characters max in this field
* Fixed JavaScript error causing **Search** page to crash due to missing `user_metadata` property in anonymous/unauthenticated users
* Udpated open office hour date info and sign-up form link
> Connects to #261. GA4 event tracking updates.

- public/index.html
- src/AnnouncementsPage/announcementsPage.jsx
- src/Auth/authReducer.js
- src/BrowseDataPage/browseDataActions.js
- src/BrowseDataPage/browseDataPage.jsx
- src/BrowseDataPage/browseDataTable.jsx
- src/BrowseDataPage/components/bundleDownloadButton.jsx
- src/LandingPage/announcementBanner.jsx
- src/LandingPage/landingPage.jsx
- src/LandingPage/promoteBanner.jsx
- src/ReleasePage/releaseEntry.jsx
- src/ReleasePage/releasePage.jsx
- src/Search/searchPage.jsx
- src/testData/testUser.json
* Added Siteimprove Analytics script to `index.html` header to track site usage through [Stanford's Siteimprove service](https://my2.siteimprove.com/).
* Updated GA4 event tracking implementation to replace name/email values with `userid`s pertinent to data access/download events.
> Connects to #263. GA4 Event Name value correctoion and Siteimprove Analytics addition.

- src/LandingPage/promoteBanner.jsx
Updated the implementation of the BIC Open Office Hour announcement on homepage in the attempt to reduce monthly production deployment.
> Connects to #269. Open office hour announcement on homepage.

- src/LandingPage/components/figure1c.jsx
- src/LandingPage/components/figure1c_data.json
- src/LandingPage/components/figureTissueProps.json
- src/LandingPage/landingPage.jsx
- src/sass/_landingPage.scss
Deprecated the static Figure 1C SVG image on the redesigned homepage, and replaced it with an interactive plot natively built with *D3*.
> Connects to #265. Homepage redesign UI enhancement.

- README.md
- src/DataStatusPage/common.jsx
- src/DataStatusPage/dataStatusActions.js
- src/DataStatusPage/dataStatusPage.jsx
- src/DataStatusPage/dataStatusReducer.js
- src/DataStatusPage/qcReportHelp.jsx
- src/DataStatusPage/sharelib/qcReportButtonList.js
- src/DataStatusPage/sharelib/qcReportByPhaseOmicPrefix.js
Closes #276.
Add an additional tab to the QC data monitor to show QC results for methylcap-seq data submissions.
Tested in the development environment by checking the QC data monitor output against the development database.
Did reveal that the issue [#95](https://github.com/MoTrPAC/qc-automation/issues/95) in the QC automation repo does have some downstream effects on the `Phase` tab of the QC data monitor.
> Add MethylCap-seq Tab

- .circleci/config.yml
Bumping `node` version to `v20.11.0` due to its incompatibility with `polished@4.3.0` during `yarn install`, including `circleci` config.
> Bump node version to v20.11.0

- package.json
Bump `victory` dependency version due to failed production build during deployment.
> Bump dependency version

- src/MultiOmicsWorkingGroups/multiOmicsWorkingGroups.jsx
* Added new BIC Updates section to the Multi-omics working groups resources page.
* Fixed PRE-CAWG section title
* Updated DAWG-PAC section title
* Updated some DAWG-PAC list/link text
* Fixed the HTML page title
> Connects to #298. Multi-omics working groups resources update.

- src/App/App.jsx
- src/App/__test__/App.test.jsx
- src/Navbar/navbar.jsx
- src/Publications/Docs/Protocol/Clinical/clinicalStudyProtocols.jsx
- src/RelatedStudy/heritageProteomics.jsx
* Implemented new page to host links to MoTrPAC clinical study protocols and MOPs with temporary restricted access to internal users until manuscript is accepted at JAP.
* Changed HERITAGE proteomics data file links (see `/related-studies/heritage-proteomics`) to zipped files on Google Drive due to the deprecation of publicly accessible GCP bucket.
> Connects to #300. Connects to #301. New UI for clinical study protocols and MOPs. Updated links to HERITAGE proteomics data files.

- public/static-assets/dawg-pac/phenotypes/pass1ac-pheno-analysis.html
- src/MultiOmicsWorkingGroups/dawgPAC.jsx
* Added new DAWG-PAC analysis list item for phenotype with a link to the notebook file.
> Connects to #367. DAWG-PAC analysis resources update.

- src/AnalysisPage/GraphicalClustering/sharedLib.js
- src/LandingPage/components/backgroundVideo.jsx
- src/Publications/Data/Animal/Phenotype/fullTableEnduranceTraining.jsx
- src/Search/featureLinks.jsx
- src/sass/search/_search.scss
* Added feature panel/card for linking out to PreCAWG data visualization tool from **Search** page. This feature panel is only presented to consortium members upon successful login.
* Suppressed the feature panel for **Data Releases** on **Search** page for now.
* Changed GCP CDN to AWS CloudFront CDN for the PASS1B-06 graphical clustering data analysis images as well as for the homepage background image.
> Connects to #370. Linkout to PreCAWG data visualization tool.

- src/GoogleAnalytics/googleAnalytics.jsx
Fixes [https://github.com/MoTrPAC/motrpac-frontend/security/code-scanning/2](https://github.com/MoTrPAC/motrpac-frontend/security/code-scanning/2)
To fix the problem, we need to add an anchor at the end of the regular expression to ensure it matches the entire hostname string. This can be done by adding a `$` at the end of the pattern. This change will ensure that only hostnames that exactly match the specified pattern will be considered valid.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
> Fix code scanning alert no. 2: Missing regular expression anchor

- src/MultiOmicsWorkingGroups/dawgPAC.jsx
- src/MultiOmicsWorkingGroups/preCAWG.jsx
* Corrected DAWG-PAC Methods link to Google Drive
* Added link to PreCAWG latest data freeze release notes
> Connects to #369. Links to DAWG-PAC and PreCAWG latest data freeze release notes.

- src/BrowseDataPage/helper.jsx
- src/DataStatusPage/dataStatusPage.jsx
- src/sass/dataStatus/_dataStatusTable.scss
* Implemented temp fix for customized file download filtering bug that affected human precovid omics data associated with adipose tissue. The permanent fix will be correcting the typo in the metadata and reindexing it.
* Added external links to individual omics (metabolomics, proteomics, GET) data transfer guidelines within the QC Data Monitor UIs.
> Connects to #384. Customized file download filtering bug.
